name: Build and Release

on:
  push:
    branches:
      - main  # 当推送到main分支时触发
  workflow_dispatch:  # 也可以手动触发

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Run build script
        run: python build.py

      - name: Read version from file
        id: version
        run: |
          $version = Get-Content VERSION | Select-String -Pattern '^v.*' | Select-Object -First 1
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: VERSION
          files: |
            dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
