name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # 也可以手动触发

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Nuitka dependencies
        run: |
          pip install nuitka

      - name: Setup Nuitka dependency cache
        shell: pwsh
        run: |
          $cachePath = "$env:LOCALAPPDATA\Nuitka\Nuitka\Cache\Downloads\depends\x86_64"
          Write-Host "Creating cache directory at $cachePath"
          New-Item -ItemType Directory -Force -Path $cachePath | Out-Null
          Copy-Item "tools\depends22_x64.zip" "$cachePath\depends22_x64.zip" -Force
          Write-Host "✅ depends22_x64.zip placed successfully"

      - name: Install MinGW
        run: |
            choco install mingw -y
            echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

      - name: Run Nuitka build script
        run: python build.py

      - name: Read version from build script
        id: version
        run: |
          $version = python -c "import build; print(build.__version__)"
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            ## ShigureAI ${{ steps.version.outputs.version }}
            
            ### 优化说明
            - 使用 Nuitka 编译，体积更小，启动更快
            - 排除了未使用的Qt模块和第三方库
            - 启用了LTO链接时优化
            - 禁用了文档字符串和断言以减小体积
            
            ### 文件说明
            - `ShigureAI_v0.0.3.exe`: 主程序可执行文件
          files: |
            ShigureAI_v0.0.3.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
